[package]
name = "chippy"
version = "0.1.0"
authors = ["Pedro Rodrigues <csixteen@protonmail.com>"]
edition = "2018"
description = "A CHIP-8 Interpreter written in Rust"

[dependencies]
clap = "2.33.0"
rand = "0.8.3"
sdl2 = "0.34"
