name: CI

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - staging
      - trying

jobs:

  build:
    name: ${{ matrix.task.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        task:
          - name: Format
            run: cargo fmt
          - name: Clippy
            run: cargo clippy
          - name: Build
            run: cargo build
          - name: Test
            run: cargo test
    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev libsdl2-gfx-dev
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}

  done:
    name: Done
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done
